language: node_js
notifications:
  email: kai.liang@jumpraw.com
node_js:
- '8'
install:
- yarn
cache: yarn
deploy:
  provider: script
  script: deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_d78d9f3194cf_key -iv $encrypted_d78d9f3194cf_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
  - ssh root@47.93.63.88 "./auto.sh"
addons:
  ssh_known_hosts: 47.93.63.88 # 请替换成自己的服务器IP

