language: node_js
notifications:
  email: kai.liang@jumpraw.com
node_js:
- '8'
install:
- yarn
# - npm
cache:
  directories:
  - node_modules
# deploy:
#   provider: script
#   script: deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_d78d9f3194cf_key -iv $encrypted_d78d9f3194cf_iv
  -in deploy_key.enc -out ./deploy_key -d
# - openssl aes-256-cbc -K $encrypted_d78d9f3194cf_key -iv $encrypted_d78d9f3194cf_iv
#   -in id_rsa.enc -out ~\/.ssh/id_rsa -d
# - chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
# - ssh -i ./deploy_key root@$SERVER_IP_ADDRESS
after_success:
# - npm install pm2 -g
- pwd
- scp -o StrictHostKeyChecking=no -r dist/  root@$SERVER_IP_ADDRESS:/root/vue-hackernews-2.0/
- ./auto.sh
# - if [ $TRAVIS_PULL_REQUEST_BRANCH ]; then
#     sh .bin/deploy.sh;
#   fi
# - sh ./bin/deploy.sh;
addons:
  ssh_known_hosts: 47.93.63.88
script:
- yarn run build
# - yarn run build
# - yarn start
