language: node_js
notifications:
  email: kai.liang@jumpraw.com
node_js:
- '8'
install:
- yarn
cache: yarn
deploy:
  provider: script
  script: deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_d78d9f3194cf_key -iv $encrypted_d78d9f3194cf_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
# - ssh -i ./deploy_key root@$SERVER_IP_ADDRESS pwd
after_success:
- ssh -i ./deploy_key root@$SERVER_IP_ADDRESS "./auto.sh"
addons:
  ssh_known_hosts: '$SERVER_IP_ADDRESS'
